-- Auto-generated by tools/build_maps.py - do not edit. Detailed town maps: parent region
-- + world->map data. crop = the region global-map-pixel rectangle the map covers
-- {posX,posY,W,H}; active = the trigger area {x,y,w,h,ellipse} (same pixel frame).
MinimapLocalMaps = {
   apolena = { region = "trosecko", inside = 0, crop = {4420, 924, 2098, 2899}, active = {5149, 1579, 483, 1470, 0} },
   bohounovice = { region = "kutnohorsko", inside = 0, crop = {2635, 792, 2329, 2453}, active = {3539, 1789, 616, 563, 1} },
   bylany = { region = "kutnohorsko", inside = 0, crop = {5937, 4789, 2602, 2539}, active = {6785, 5612, 935, 893, 1} },
   certovka = { region = "kutnohorsko", inside = 0, crop = {5025, 342, 2222, 2222}, active = {5868, 1246, 541, 478, 1} },
   grunta = { region = "kutnohorsko", inside = 0, crop = {6251, 796, 2604, 2763}, active = {7114, 1607, 929, 931, 1} },
   horany = { region = "kutnohorsko", inside = 0, crop = {4845, 1009, 2659, 2660}, active = {5688, 2036, 808, 714, 1} },
   klaster_interior = { region = "klaster", inside = 1, crop = {2913, 2148, 1062, 935}, active = {2913, 2148, 1062, 935, 1}, inside_areas = {{1356.3, 1034.7, 1355.1, 1035.3, 1352.1, 1031.1, 1344.0, 1035.9, 1340.9, 1032.0, 1360.6, 1011.6, 1364.7, 1016.9, 1376.4, 1008.1, 1373.1, 1003.2, 1371.7, 1002.0, 1369.0, 1002.8, 1354.5, 984.7, 1345.8, 973.5, 1336.9, 980.4, 1337.0, 985.2, 1316.9, 1000.5, 1305.1, 986.1, 1291.7, 996.1, 1302.6, 1010.4, 1279.4, 1027.7, 1274.7, 1021.2, 1266.3, 1027.5, 1282.9, 1050.8, 1279.2, 1054.6, 1282.9, 1059.5, 1287.4, 1056.3, 1304.1, 1078.7, 1318.7, 1098.1, 1355.2, 1071.7, 1358.4, 1075.8, 1375.7, 1063.1, 1372.9, 1058.3, 1380.1, 1052.2, 1382.1, 1048.9, 1383.2, 1041.8, 1382.2, 1038.2, 1377.6, 1032.1, 1374.6, 1030.2, 1369.5, 1029.2, 1367.5, 1029.0, 1361.3, 1030.9}, {1390.1, 985.2, 1378.7, 995.9, 1403.4, 1022.7, 1415.6, 1010.0, 1400.1, 994.5}} },
   kutna_hora = { region = "kutnohorsko", inside = 0, crop = {7667, 2649, 4314, 3994}, active = {8748, 3700, 1935, 1705, 1} },
   malesov = { region = "kutnohorsko", inside = 0, crop = {5238, 7629, 2579, 2544}, active = {6048, 8543, 913, 807, 1} },
   miskovice = { region = "kutnohorsko", inside = 0, crop = {4085, 3546, 2761, 2762}, active = {4930, 4373, 1038, 1130, 1} },
   nebakov = { region = "trosecko", inside = 0, crop = {2266, 3863, 2262, 2154}, active = {2912, 4509, 970, 862, 1} },
   nomad_camp = { region = "trosecko", inside = 0, crop = {320, 2578, 1935, 1814}, active = {1030, 3290, 651, 546, 1} },
   opatovice = { region = "kutnohorsko", inside = 0, crop = {3241, 1904, 2504, 2805}, active = {4082, 2721, 757, 1186, 1} },
   pritoky = { region = "kutnohorsko", inside = 0, crop = {5709, 2934, 2374, 2511}, active = {6561, 3812, 652, 582, 1} },
   ratbor = { region = "kutnohorsko", inside = 0, crop = {1494, 824, 2762, 2761}, active = {2362, 1630, 1073, 1143, 1} },
   semin = { region = "trosecko", inside = 0, crop = {1165, 2927, 2416, 2250}, active = {1824, 3625, 1098, 812, 1} },
   stara_kutna = { region = "kutnohorsko", inside = 0, crop = {7164, 2352, 2657, 2414}, active = {8035, 3165, 917, 686, 1} },
   suchdol = { region = "kutnohorsko", inside = 0, crop = {934, 3056, 2629, 2626}, active = {1785, 3861, 796, 995, 1} },
   tachov = { region = "trosecko", inside = 0, crop = {2148, 762, 2432, 2431}, active = {2791, 1421, 1110, 1129, 1} },
   troskovice = { region = "trosecko", inside = 0, crop = {3080, 1745, 2772, 2436}, active = {3833, 2787, 851, 662, 1} },
   trosky = { region = "trosecko", inside = 0, crop = {3451, 668, 2430, 2135}, active = {4106, 1495, 818, 655, 1} },
   vysoka = { region = "kutnohorsko", inside = 0, crop = {1862, 4455, 2374, 2603}, active = {2702, 5295, 736, 950, 1} },
   zelejov = { region = "trosecko", inside = 0, crop = {1586, 1794, 2432, 2432}, active = {2220, 2600, 1083, 966, 1} },
}
