-- AUTO-GENERATED by tools/gen_poi.py — do not hand-edit the catalog.
-- Named locations in GLOBAL map space (position_x/y from ui_map_label.xml).
-- Shown only when minimap_catalog is on AND globalCal is calibrated.
MinimapData = MinimapData or {}
MinimapData.catalog = {
  trosecko = {
    { x = 5275, y = 2413, type = 0, name = 'location_apolena' },
    { x = 1318, y = 3318, type = 0, name = 'location_cikanskyTabor' },
    { x = 4390, y = 1603, type = 0, name = 'location_hradTrosky' },
    { x = 2449, y = 4085, type = 0, name = 'location_semin' },
    { x = 3591, y = 1905, type = 0, name = 'location_tachov' },
    { x = 4028, y = 2908, type = 0, name = 'location_troskovice' },
    { x = 3187, y = 4828, type = 0, name = 'location_tvrzNebakov' },
    { x = 2778, y = 3065, type = 0, name = 'location_zelejov' },
  },
  kutnohorsko = {
    { x = 3991, y = 1899, type = 0, name = 'location_bohounovice' },
    { x = 7289, y = 5895, type = 0, name = 'location_bylany' },
    { x = 6141, y = 1291, type = 0, name = 'location_certovka' },
    { x = 7738, y = 1853, type = 0, name = 'location_grunta' },
    { x = 6194, y = 2249, type = 0, name = 'location_horany' },
    { x = 10010, y = 4498, type = 0, name = 'location_kutnaHora' },
    { x = 6403, y = 8718, type = 0, name = 'location_malesov' },
    { x = 5614, y = 4722, type = 0, name = 'location_miskovice' },
    { x = 4234, y = 2666, type = 0, name = 'location_opatovice' },
    { x = 6922, y = 3827, type = 0, name = 'location_pritoky' },
    { x = 2761, y = 1826, type = 0, name = 'location_ratbor' },
    { x = 8742, y = 3359, type = 0, name = 'location_staraKutna' },
    { x = 2433, y = 4092, type = 0, name = 'location_suchdol' },
    { x = 3175, y = 5673, type = 0, name = 'location_vysoka' },
    { x = 4466, y = 3220, type = 0, name = 'location_zikmunduvTabor' },
  },
  klaster = {
  },
}

-- Per-level GLOBAL -> ENTITY(world) transform: world = (global - off) / scale.
-- Defaults are PLACEHOLDERS. Calibrate in-game: stand at a known town,
-- run minimap_calibrate to read world x/y, find that town's global x/y above,
-- then minimap_setcal <offx> <offy> [scale]  (offx = global_x - world_x).
MinimapData.globalCal = {
  trosecko    = { scale = 1.0, offx = 4096, offy = 4096 },
  kutnohorsko = { scale = 1.0, offx = 6000, offy = 4096 },
  klaster     = { scale = 1.0, offx = 4096, offy = 4096 },
}

